### ISSUE TITLE
Trying to send a PRG to devkit on latest ROMs fails with M65.exe

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/m65connect#6]
![image](https://user-images.githubusercontent.com/4640763/114321485-ddedd500-9b12-11eb-96f5-8c7c30b56c90.png)

When sending a PRG to the devkit via M65.exe the above message occurs. This was working fine on 911210.bin, and has been an issue on all newer ROMS I have tried over the last 3 months. Raising it here so it can be looked into

**Comment by Taygair** [comment]
I have done some analysis on which version prg file send fails (it's m65 in general, not only m65.exe):

920133.BIN to and with 920155.BIN :
> DOS: 62,FILE NOT FOUND,00,00
(m65 freezes)

920119.BIN to and with 920132.BIN :
> MEGA65 screen freezes after showing "RUN")

till and with 920118.BIN :
> PRG file load works with m65


-> Some changes in **920119.BIN** and **920133.BIN** are leading to a problem where prg files won't run anymore.

**Comment by gardners** [comment]
It's most likely that m65 is setting the LOAD trap on a particular address, that is no longer correct in the patched ROMs. The issue should thus really be on mega65-tools, not here. There might already be an issue there, in which case it would be good to include a link here, so that people searching here will find it.

The solution for the m65 programme is for it to read the LOAD vector, and get the address from that, instead of just having a hard-wired address.

**Comment by Taygair** [comment]
Seems to be a problem in m65 in releation with ROM changes and is already mentioned here: https://github.com/MEGA65/mega65-tools/issues/2

**Comment by Taygair** [comment]
Fixed with one of the latest version
